version: "3.9"

services:
  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: 'rabbitmq'
    ports:
        - 5672:5672
        - 15672:15672
    volumes:
        - $PWD:/var/lib/rabbitmq/
        - $PWD:/var/log/rabbitmq
    networks:
        - rabbitmq_go_net
  rabbitmq-mgn:
    container_name: rabbitmq-mgn
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      ADMINUSER: guest
      ADMINPASSWORD: guest
      LOGINACCOUNT: test
      LOGINPASSWORD: test12
      MQENDPOINT: rabbitmq
    restart: always
    networks:
        - rabbitmq_go_net
    depends_on:
      - rabbitmq
networks:
  rabbitmq_go_net:
    driver: bridge
